
[package]
name = "spl-themis-ristretto-client"
version = "0.1.0"
description = "SPL THEMIS client"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[dependencies]
bincode = "1.3"
borsh = "0.7.1"
curve25519-dalek = {package = "curve25519-dalek-ng", git = "https://github.com/garious/curve25519-dalek", rev = "fcef1fa11b3d3e89a1abf8986386ba9ae375392c", default-features = false, features = ["borsh"]}
elgamal_ristretto = { git = "https://github.com/garious/elgamal", rev = "892dbe115104bcb8cc26d79f9676c836ff6c018e", default-features = false }
futures = "0.3"
solana-banks-client = "1.6.5"
solana-cli-config = "1.6.5"
solana-sdk = "1.6.5"
spl-themis-ristretto = { version = "0.1.0", path = "../program_ristretto", features = ["no-entrypoint"] }
tarpc = { version = "0.22.0", features = ["full"] }
tokio = "0.3"
url = "2.1"

[dev-dependencies]
separator = "0.4.1"
solana-banks-server = "1.6.5"
solana-bpf-loader-program = "1.6.5"
solana-core = "1.6.5"
solana_rbpf = "0.1"
solana-runtime = "1.6.5"

[lib]
crate-type = ["cdylib", "lib"]
[patch.crates-io]
solana-account-decoder = {path = "/Users/wangge/Projects/rust/solana/account-decoder" }
solana-banks-client = { path = "/Users/wangge/Projects/rust/solana/banks-client"}
solana-banks-server = { path = "/Users/wangge/Projects/rust/solana/banks-server"}
solana-bpf-loader-program = { path = "/Users/wangge/Projects/rust/solana/programs/bpf_loader" }
solana-clap-utils = {path = "/Users/wangge/Projects/rust/solana/clap-utils" }
solana-cli-config = {path = "/Users/wangge/Projects/rust/solana/cli-config" }
solana-cli-output = {path = "/Users/wangge/Projects/rust/solana/cli-output" }
solana-client = { path = "/Users/wangge/Projects/rust/solana/client"}
solana-core = { path = "/Users/wangge/Projects/rust/solana/core"}
solana-logger = {path = "/Users/wangge/Projects/rust/solana/logger" }
solana-notifier = { path = "/Users/wangge/Projects/rust/solana/notifier" }
solana-remote-wallet = {path = "/Users/wangge/Projects/rust/solana/remote-wallet" }
solana-program = { path = "/Users/wangge/Projects/rust/solana/sdk/program" }
solana-program-test = { path = "/Users/wangge/Projects/rust/solana/program-test" }
solana-runtime = { path = "/Users/wangge/Projects/rust/solana/runtime" }
solana-sdk = { path = "/Users/wangge/Projects/rust/solana/sdk" }
solana-stake-program = { path = "/Users/wangge/Projects/rust/solana/programs/stake" }
solana-transaction-status = { path = "/Users/wangge/Projects/rust/solana/transaction-status" }
solana-vote-program = { path = "/Users/wangge/Projects/rust/solana/programs/vote" }
